### ISSUE TITLE
enhanced script logging 

### ISSUE THREAD

**Issue by spali** [Homegear/Homegear#194]
before version 0.6, script output was displayed in the Homegear log which helped debugging of just scripts. It seems there changed something in version 0.6.
I know, there is (my requested) ```writeLog``` rpc method. But calling it does result in around the double time of script execution when using it a few times in the script. 
This have to be the overhead of the rpc calls. Maybe there must be a better way to archive both.

What do you think about output script output always plain in the log like previous behavior.
This would allow the script to handle how much should be logged.

I see the following advantages:
- script can still decide how much will be logged
- script can still decide based on the log level received by a single call to ```logLevel```
- script has still the possibility to send logs with ```writeLog``` to Homegear. This can be done based on the current log level which makes it more efficient except script want it to send to Homegear.

In general, I would then implements scripts as follows:
Script gets the current log level at the beginning and only sends logs based on this log level to Homegear. But the script allows local debugging by just output text, without increasing the debug level of Homegear (which would result in to much information when just the script output is required for script debugging). 
Theoretical there would also be the possibility to get STDERR output of the script on debuglevel >= 1 or maybe 2= and STDOUT only on debuglevel >= 4

Additional to this general suggestion, when using ```writeLog``` by rpc calls, at a higher log level (dont know if 4 or 5), the text is displayed twice. Once the real log line as requested by rpc call to ```writeLog``` but also again because the rpc call itself is logged.
```
04/24/15 11:19:48.459 my message
(String) my message
```
Maybe in this special case, it could make sense to hide rpc call logging itself?

**In Short :)**
Depending on what you prefer, I would wish the following concrete changes:
- Log Script Output of STDOUT to the logfile if homegear debuglevel >= 4
- Log Scipt STDERR Output to the logfile if homegear debuglevel >= 2  (1 should maybe be reserved for homegear errors)
- For the special case of RPC Method call ```writeLog``` do only print the text of the parameter and not the debug stuff of ```writeLog``` itself.

**Ferrari solution**
The above is the easier implementation, because it I could imagine also to solve this by introducing different log levels for different components. I.e. have a debug level for scripts, having a debuglevel for device communication, having a debuglevel for Homegear core stuff etc....
The cool thing here is, it makes specific debugging possible, but of course would require almost a complete new logging functionality based on the Homegear components.
Maybe this is something for 0.7 ;) and first just the simple implementation.

**Comment by spali** [comment]
:fearful: ops, just found out, parts are already solved.
I used in for version 0.5.x a wrapper shell script which called my php scripts from events, because I didn't want to rely on the decision of Homegear which script engine is used (was scarred of the sentence in the documentation of ```runScript```). But I changed now my events to call the php scripts directly and ... guess what :) 
-> Output is logged of the script, even in debug level 3, as I wanted :)

So now I see only the separation of STDERR and STDOUT as possible enhancement. (didn't test if, maybe you surprise me here too)
And maybe for long term the other suggestion of mine (separating logging by components) could be worth a thought.

**Comment by hfedcba** [comment]
I like the Ferrari solution :-P. It will be implemented eventually, but as you said, that's something for 0.7 - it's not soooo much work, as each component basically already has it's own debug level, but still...

Currently the script output is always logged (unless empty). I think it should be in the hand of the script developer if he wants to log something or not? That's why I decided to always print the script output to the console and the log file.

I think two things would be good:
* Log errors to STDERR, too
* Introduction of a PHP constant to get the current debug level. Alternatively or additionally I could add a log function for scripts which logs based an the Homegear log level (or the then newly introduced script log level)?

What do you think?

**Comment by spali** [comment]
maybe you don't have to create a log function, it could depend on my idea of the forum (grandslam, if you didn't got it already :)
Keep this Issue open for now, just to remember the Ferrari solution, I will open anyway a new Issue just for the "Proxy class" I use to see if we can integrate this into the internal script engine.

**Comment by hfedcba** [comment]
\Homegear\Homegear::log() now exists ;). Still missing is the component seperation.

**Comment by spali** [comment]
is there any difference of `\Homegear\Homegear::log()` to the `WriteLog` function which is redirected to the rpc call?
I only have seen, that the parameters of the function are reverse. But is there any other difference?

**Comment by hfedcba** [comment]
Yes, `writeLog()` writes to "homegear.log" and "homegear.err", `log()` to "homegear-scriptengine.log" and "homegear-scriptengine.err".

**Comment by spali** [comment]
:+1:  makes sense
